# action.yml
name: 'Docusaurus GitHub Action'
description: 'Deploys a Docusaurus website to GitHub Pages'
inputs:
  args:  # id of input
    description: 'Docusaurus action command'
    required: true
    default: ''
outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}