# action.yml
name: 'Docusaurus GitHub Action'
description: 'Deploys a Docusaurus website to GitHub Pages'
inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
#   args:
#     - ${{ inputs.who-to-greet }}